version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    command: uvicorn core.app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - df.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  parsers:
    build: .
    container_name: parsers_app
    command: python -m parsers
    env_file:
      - df.env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: radar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
